plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'kotlin-parcelize'
}
android {
    compileSdkVersion versions.compileSdk

    defaultConfig {
        applicationId "com.nthreads.cryptotracker"

        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    dataBinding {
        enabled true
    }
}

dependencies {

    implementation deps.androidx.appCompat
    implementation deps.androidx.materialDesign
    implementation deps.androidx.swipeToRefresh
    implementation deps.androidx.constraintLayout

    implementation deps.androidx.workManager

    implementation deps.androidx.splashScreen

    // ViewModel and LiveData
    implementation deps.androidx.lifecycleExt

    implementation deps.kotlin.ktx


    // Retrofit
    implementation deps.retrofit.retrofitLib
    implementation deps.retrofit.gsonConverter
    implementation deps.retrofit.rxJavaAdapter
    implementation deps.retrofit.loggingInterceptor

    // RxKotlin and RxAndroid
    implementation deps.reactivex.rxJava
    implementation deps.reactivex.rxAndroid

    //Test libs
    testImplementation deps.tests.jUnit
    androidTestImplementation deps.tests.workManger
    androidTestImplementation deps.tests.jUnitKtxExt
}